name: Pipeline de Integracion Continua

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Descargar el código (Checkout)
      uses: actions/checkout@v4
      
    - name: Bonus 1. Instalar Spectral (SDD)
      run: npm install -g @stoplight/spectral-cli

    - name: Bonus 2. Validar contrato de API con Spectral
      run: spectral lint openapi.yaml

    - name: 2. Configurar el entorno Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: 3. Instalar dependencias
      run: |
        pip install -r requirements.txt

    - name: 4. Ejecutar pruebas automáticas
      run: |
        pytest test_app.py

    - name: 5. Build automatizada (Docker)
      run: |
        docker build -t mi-app-demo .

    - name: 6. Mecanismo de Feedback (Discord)
      if: always()
      uses: Ilshidur/action-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: |
          Resultado de la Integración: **${{ job.status }}**
          Autor: ${{ github.actor }}
          Commit: "${{ github.event.head_commit.message }}"
          Ver auditoría de archivos: https://github.com/${{ github.repository }}/commit/${{ github.sha }}